### ISSUE TITLE
Connection details

### ISSUE THREAD

**Issue by IanK6449** [datenstau/A9_PPPP#2]
Hi, thank you for writing this script... I would not know where to start doing such a thing.
I suspect your code may work on a couple of cameras I have which use the HDWiFiCamPro app and seem to show very similar AP details etc.
But, I am not sure how to specify the IP address of my camera in your code anywhere or whether it is only supposed to work if my PC is connected directly to my camera's access point?
Apologies for the noob question but I have tried both methods and nothing seems to work. I get a 'Broadcast message sent' line on my screen that just repeats but localhost:3000 shows no image sorry.

Any pointers would be hugely appreciated.
Cheers,

IK

**Comment by IanK6449** [comment]
This is the error message I receive when connected to the camera's AP and hit ctrl-c on the run.js script:

**Comment by IanK6449** [comment]
internal/validators.js:217
    throw new ERR_SOCKET_BAD_PORT(name, port, allowZero);
    ^

RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received undefined.
    at validatePort (internal/validators.js:217:11)
    at Socket.send (dgram.js:629:12)
    at PPPP.send (C:\Users\ikite\Downloads\A9_PPPP-master\A9_PPPP-master\pppp.js:219:17)
    at PPPP.sendEnc (C:\Users\ikite\Downloads\A9_PPPP-master\A9_PPPP-master\pppp.js:209:10)
    at PPPP.destroy (C:\Users\ikite\Downloads\A9_PPPP-master\A9_PPPP-master\pppp.js:406:10)
    at process.<anonymous> (C:\Users\ikite\Downloads\A9_PPPP-master\A9_PPPP-master\run.js:46:5)
    at process.emit (events.js:400:28) {
  code: 'ERR_SOCKET_BAD_PORT'
}

**Comment by IanK6449** [comment]
Also, my camera's AP starts with DGOC rather than DGOA so this may be a different camera variant perhaps. I couldn't see any packets from its IP address in Wireshark but I am also very much a noob at that too so am probably missing how to find them.

**Comment by datenstau** [comment]
Hi @IanK6449,
There is no place to specify the IP address in my script. The script sends a broadcast packet and the camera should respond to it. Only after receiving a response from the camera, we know the IP.

You mentioned, your camera uses a DGOC prefix. I think there must be a difference in the broadcast packet. Unfortunately, I don't have a DGOC camera, so I can't test it.

This explains why you are stuck at the 'Broadcast message sent' line. Your camera never responds, so we don't have the IP and port. The error message when you hit ctrl-c just says that we don't have a valid port to tell the camera to close the connection.  

You can try switching your computer's WiFi device in monitor mode (if supported) and connect your phone to the camera's access point. If you monitor the right channel, you should be able to see the traffic between the camera and your phone. Maybe you can identify any broadcast messages that appear while starting the HDWifiCamPro app.

**Comment by IanK6449** [comment]
Thanks for the thorough reply mate.
Yeah I suspect you’re right about the DGOC message requiring a different packet somewhere along the line.
I will try to grab the packet as you suggest and see what the data looks like.
If I do manage to identify it, where in your code would I make the change?

Cheers,

IK

**Comment by datenstau** [comment]
Hi,

for DGOA prefix, the app sends a UDP packet to a broadcast IP like 192.168.0.255 on port 32108.
The message is `2cba5f5d` in my case.

If you are able to capture the traffic and the message is different, you should change line 191 in pppp.js.

The port could be different, too.

**Comment by IanK6449** [comment]
Hi,

So, I endeavoured to capture the packets and I can see a lot of them.
But there does seem to be one to port 32108 but with a different code (2c ba 5f 5d).
I tried changing that code as you suggested and also tried a few other ports too but I still get the same error message – bad port.

Oddly, one of the packets did contain your exact code and was to port 32108 so maybe that’s correct and something else is wrong with my underlying node installation so I’ll look into that too first.

Thanks for your ongoing help either way!

IK

**Comment by UraniumDonut** [comment]
I had a very similar issue. DGOC- prefix, didn't work, AP mode. 

I fixed it, by disabling all other network interfaces. If I am directly connected to the camera it works, but if I (for example) plug in an additional LAN cable, it breaks, and is stuck on "Broadcast message sent."

HB6_V1.0D211125 is the pcb marking

Maybe the script tries some limited broadcast on the first interface?

**Comment by antonio-a2m** [comment]
@datenstau : I would like to collaborate with this repo: I made a couple of changes:

- Added the npm package called commander in order to pass parameters to the command. In those parameters now it is possible to set:
- Port number, in order to run more than one server
- Ip address of the interface to use instead of broadcast, in the case there is more than one interface, so the broadcast can be bound to a certain interface.
- Ip address of the camera: instead of sending a broadcast, it sends the packet directly to the camera.

The changes are ready to be pushed to a new branch, so I can ask for a pull request, I just need the permissions for doing that in this repo.

Thank you

**Comment by Silasso** [comment]
After monitoring the packets from the app myself, i can confirm that the code(2cba5f5d) and port(32108) are correct, only the broadcast ip 255.255.255.255 was wrong, cause the app sends to 192.168.0.255
just change that in pppp.js(Line 194) and it should work with DGOC- prefix.

pcb-mark: HB3_V1.7D20607

**Comment by datenstau** [comment]
@antonio-a2m Thanks for adding the command line options! And @Silasso, thanks for testing the DGOC prefix, too!

If I remember correctly, when I was testing and capturing packets, the app was sending on my local network's broadcast IP, too. I changed it to 255.255.255.255, expecting it to just work in every network.

**Comment by Silasso** [comment]
If you are using a cam with DOGF- prefix, you need to change in pppp.js(Line 194) the address to 192.168.1.255 worked for me flawlessly. Maybe also add that to readme.😉

**Comment by datenstau** [comment]
@Silasso Thank you for testing a DOGF-prefix camera! 
Please pull the newest version of this project. Since @antonio-a2m  added a command line option to specify the broadcast address, there's no need to manually change IP addresses in pppp.js.

**Comment by Apache02** [comment]
pcb mark HB6_V1.0D211125
AP prefix: DGO-

works fine!

**Comment by danka621** [comment]
I am running "node run.js -b 192.168.1.255" and am getting the response "broadcast Message sent." repeatedly. 
I can see the web interface on http://localhost:3000/, but there are no camera or audio streams.

My camera AP has the prefix **DGOI-**.
Marking on the board: **HQT6_V0.2 D231205**.
![package](https://github.com/datenstau/A9_PPPP/assets/131620546/fbcf5612-de15-4a96-98ec-615c57d0cfce)

**Comment by danka621** [comment]
I am running "node run.js -b 192.168.1.255" and am getting the response "broadcast Message sent." repeatedly.
I can see the web interface on http://localhost:3000/, but there are no camera or audio streams.

My camera AP has the prefix **DGOI-**.
Marking on the board: **HQT6_V0.2 D231205**.
